package com.viroyal.doormagnet.devicemng.model;

public class DeviceSwitchSetting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_switch_setting.id
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_switch_setting.imei
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_switch_setting.switchControlOne
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    private Integer switchcontrolone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_switch_setting.switchControlTwo
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    private Integer switchcontroltwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_switch_setting.switchControlThree
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    private Integer switchcontrolthree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_switch_setting.mid
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    private String mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_switch_setting.id
     *
     * @return the value of t_device_switch_setting.id
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_switch_setting.id
     *
     * @param id the value for t_device_switch_setting.id
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_switch_setting.imei
     *
     * @return the value of t_device_switch_setting.imei
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_switch_setting.imei
     *
     * @param imei the value for t_device_switch_setting.imei
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_switch_setting.switchControlOne
     *
     * @return the value of t_device_switch_setting.switchControlOne
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    public Integer getSwitchcontrolone() {
        return switchcontrolone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_switch_setting.switchControlOne
     *
     * @param switchcontrolone the value for t_device_switch_setting.switchControlOne
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    public void setSwitchcontrolone(Integer switchcontrolone) {
        this.switchcontrolone = switchcontrolone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_switch_setting.switchControlTwo
     *
     * @return the value of t_device_switch_setting.switchControlTwo
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    public Integer getSwitchcontroltwo() {
        return switchcontroltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_switch_setting.switchControlTwo
     *
     * @param switchcontroltwo the value for t_device_switch_setting.switchControlTwo
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    public void setSwitchcontroltwo(Integer switchcontroltwo) {
        this.switchcontroltwo = switchcontroltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_switch_setting.switchControlThree
     *
     * @return the value of t_device_switch_setting.switchControlThree
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    public Integer getSwitchcontrolthree() {
        return switchcontrolthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_switch_setting.switchControlThree
     *
     * @param switchcontrolthree the value for t_device_switch_setting.switchControlThree
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    public void setSwitchcontrolthree(Integer switchcontrolthree) {
        this.switchcontrolthree = switchcontrolthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_switch_setting.mid
     *
     * @return the value of t_device_switch_setting.mid
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_switch_setting.mid
     *
     * @param mid the value for t_device_switch_setting.mid
     *
     * @mbg.generated Fri Jan 17 11:23:41 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid;
    }
}