package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

public class DeviceReportPowerConsumptionAbnormal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_powerconsumptionabnormal.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_powerconsumptionabnormal.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_powerconsumptionabnormal.powerConsumptionIntegerPart
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Integer powerconsumptionintegerpart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_powerconsumptionabnormal.powerConsumptionDecimalPart
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Integer powerconsumptiondecimalpart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_powerconsumptionabnormal.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_powerconsumptionabnormal.id
     *
     * @return the value of t_device_report_powerconsumptionabnormal.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_powerconsumptionabnormal.id
     *
     * @param id the value for t_device_report_powerconsumptionabnormal.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_powerconsumptionabnormal.imei
     *
     * @return the value of t_device_report_powerconsumptionabnormal.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_powerconsumptionabnormal.imei
     *
     * @param imei the value for t_device_report_powerconsumptionabnormal.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_powerconsumptionabnormal.powerConsumptionIntegerPart
     *
     * @return the value of t_device_report_powerconsumptionabnormal.powerConsumptionIntegerPart
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Integer getPowerconsumptionintegerpart() {
        return powerconsumptionintegerpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_powerconsumptionabnormal.powerConsumptionIntegerPart
     *
     * @param powerconsumptionintegerpart the value for t_device_report_powerconsumptionabnormal.powerConsumptionIntegerPart
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setPowerconsumptionintegerpart(Integer powerconsumptionintegerpart) {
        this.powerconsumptionintegerpart = powerconsumptionintegerpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_powerconsumptionabnormal.powerConsumptionDecimalPart
     *
     * @return the value of t_device_report_powerconsumptionabnormal.powerConsumptionDecimalPart
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Integer getPowerconsumptiondecimalpart() {
        return powerconsumptiondecimalpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_powerconsumptionabnormal.powerConsumptionDecimalPart
     *
     * @param powerconsumptiondecimalpart the value for t_device_report_powerconsumptionabnormal.powerConsumptionDecimalPart
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setPowerconsumptiondecimalpart(Integer powerconsumptiondecimalpart) {
        this.powerconsumptiondecimalpart = powerconsumptiondecimalpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_powerconsumptionabnormal.time
     *
     * @return the value of t_device_report_powerconsumptionabnormal.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_powerconsumptionabnormal.time
     *
     * @param time the value for t_device_report_powerconsumptionabnormal.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}