package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

public class DeviceReportSoftVersion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_softversion.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_softversion.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_softversion.softversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private String softversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_softversion.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_softversion.id
     *
     * @return the value of t_device_report_softversion.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_softversion.id
     *
     * @param id the value for t_device_report_softversion.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_softversion.imei
     *
     * @return the value of t_device_report_softversion.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_softversion.imei
     *
     * @param imei the value for t_device_report_softversion.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_softversion.softversion
     *
     * @return the value of t_device_report_softversion.softversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public String getSoftversion() {
        return softversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_softversion.softversion
     *
     * @param softversion the value for t_device_report_softversion.softversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setSoftversion(String softversion) {
        this.softversion = softversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_softversion.time
     *
     * @return the value of t_device_report_softversion.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_softversion.time
     *
     * @param time the value for t_device_report_softversion.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}