package com.viroyal.doormagnet.devicemng.model;

public class DeviceStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.id
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.imei
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.voltage
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer voltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.current
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer current;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.activePower
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer activepower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.reactivePower
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer reactivepower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.powerfactor
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer powerfactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.temperature
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.powerConsumptionIntegerPart
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer powerconsumptionintegerpart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.powerConsumptionDecimalPart
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer powerconsumptiondecimalpart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.brightnessControlOne
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer brightnesscontrolone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.brightnessControlTwo
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer brightnesscontroltwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.brightnessControlThree
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer brightnesscontrolthree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.switchControlOne
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer switchcontrolone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.switchControlTwo
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer switchcontroltwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.switchControlThree
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer switchcontrolthree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.signalStrengthAbsoluteValue
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer signalstrengthabsolutevalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.dimmingMode
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer dimmingmode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.abnormalFlag
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer abnormalflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.angleOne
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer angleone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.angleTwo
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer angletwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.angleOriginalOne
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer angleoriginalone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.angleOriginalTwo
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    private Integer angleoriginaltwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.id
     *
     * @return the value of t_device_status.id
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.id
     *
     * @param id the value for t_device_status.id
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.imei
     *
     * @return the value of t_device_status.imei
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.imei
     *
     * @param imei the value for t_device_status.imei
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.voltage
     *
     * @return the value of t_device_status.voltage
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.voltage
     *
     * @param voltage the value for t_device_status.voltage
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setVoltage(Integer voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.current
     *
     * @return the value of t_device_status.current
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getCurrent() {
        return current;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.current
     *
     * @param current the value for t_device_status.current
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setCurrent(Integer current) {
        this.current = current;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.activePower
     *
     * @return the value of t_device_status.activePower
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getActivepower() {
        return activepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.activePower
     *
     * @param activepower the value for t_device_status.activePower
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setActivepower(Integer activepower) {
        this.activepower = activepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.reactivePower
     *
     * @return the value of t_device_status.reactivePower
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getReactivepower() {
        return reactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.reactivePower
     *
     * @param reactivepower the value for t_device_status.reactivePower
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setReactivepower(Integer reactivepower) {
        this.reactivepower = reactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.powerfactor
     *
     * @return the value of t_device_status.powerfactor
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getPowerfactor() {
        return powerfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.powerfactor
     *
     * @param powerfactor the value for t_device_status.powerfactor
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setPowerfactor(Integer powerfactor) {
        this.powerfactor = powerfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.temperature
     *
     * @return the value of t_device_status.temperature
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.temperature
     *
     * @param temperature the value for t_device_status.temperature
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setTemperature(Integer temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.powerConsumptionIntegerPart
     *
     * @return the value of t_device_status.powerConsumptionIntegerPart
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getPowerconsumptionintegerpart() {
        return powerconsumptionintegerpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.powerConsumptionIntegerPart
     *
     * @param powerconsumptionintegerpart the value for t_device_status.powerConsumptionIntegerPart
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setPowerconsumptionintegerpart(Integer powerconsumptionintegerpart) {
        this.powerconsumptionintegerpart = powerconsumptionintegerpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.powerConsumptionDecimalPart
     *
     * @return the value of t_device_status.powerConsumptionDecimalPart
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getPowerconsumptiondecimalpart() {
        return powerconsumptiondecimalpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.powerConsumptionDecimalPart
     *
     * @param powerconsumptiondecimalpart the value for t_device_status.powerConsumptionDecimalPart
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setPowerconsumptiondecimalpart(Integer powerconsumptiondecimalpart) {
        this.powerconsumptiondecimalpart = powerconsumptiondecimalpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.brightnessControlOne
     *
     * @return the value of t_device_status.brightnessControlOne
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getBrightnesscontrolone() {
        return brightnesscontrolone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.brightnessControlOne
     *
     * @param brightnesscontrolone the value for t_device_status.brightnessControlOne
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setBrightnesscontrolone(Integer brightnesscontrolone) {
        this.brightnesscontrolone = brightnesscontrolone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.brightnessControlTwo
     *
     * @return the value of t_device_status.brightnessControlTwo
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getBrightnesscontroltwo() {
        return brightnesscontroltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.brightnessControlTwo
     *
     * @param brightnesscontroltwo the value for t_device_status.brightnessControlTwo
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setBrightnesscontroltwo(Integer brightnesscontroltwo) {
        this.brightnesscontroltwo = brightnesscontroltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.brightnessControlThree
     *
     * @return the value of t_device_status.brightnessControlThree
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getBrightnesscontrolthree() {
        return brightnesscontrolthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.brightnessControlThree
     *
     * @param brightnesscontrolthree the value for t_device_status.brightnessControlThree
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setBrightnesscontrolthree(Integer brightnesscontrolthree) {
        this.brightnesscontrolthree = brightnesscontrolthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.switchControlOne
     *
     * @return the value of t_device_status.switchControlOne
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getSwitchcontrolone() {
        return switchcontrolone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.switchControlOne
     *
     * @param switchcontrolone the value for t_device_status.switchControlOne
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setSwitchcontrolone(Integer switchcontrolone) {
        this.switchcontrolone = switchcontrolone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.switchControlTwo
     *
     * @return the value of t_device_status.switchControlTwo
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getSwitchcontroltwo() {
        return switchcontroltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.switchControlTwo
     *
     * @param switchcontroltwo the value for t_device_status.switchControlTwo
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setSwitchcontroltwo(Integer switchcontroltwo) {
        this.switchcontroltwo = switchcontroltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.switchControlThree
     *
     * @return the value of t_device_status.switchControlThree
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getSwitchcontrolthree() {
        return switchcontrolthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.switchControlThree
     *
     * @param switchcontrolthree the value for t_device_status.switchControlThree
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setSwitchcontrolthree(Integer switchcontrolthree) {
        this.switchcontrolthree = switchcontrolthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.signalStrengthAbsoluteValue
     *
     * @return the value of t_device_status.signalStrengthAbsoluteValue
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getSignalstrengthabsolutevalue() {
        return signalstrengthabsolutevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.signalStrengthAbsoluteValue
     *
     * @param signalstrengthabsolutevalue the value for t_device_status.signalStrengthAbsoluteValue
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setSignalstrengthabsolutevalue(Integer signalstrengthabsolutevalue) {
        this.signalstrengthabsolutevalue = signalstrengthabsolutevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.dimmingMode
     *
     * @return the value of t_device_status.dimmingMode
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getDimmingmode() {
        return dimmingmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.dimmingMode
     *
     * @param dimmingmode the value for t_device_status.dimmingMode
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setDimmingmode(Integer dimmingmode) {
        this.dimmingmode = dimmingmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.abnormalFlag
     *
     * @return the value of t_device_status.abnormalFlag
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getAbnormalflag() {
        return abnormalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.abnormalFlag
     *
     * @param abnormalflag the value for t_device_status.abnormalFlag
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setAbnormalflag(Integer abnormalflag) {
        this.abnormalflag = abnormalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.angleOne
     *
     * @return the value of t_device_status.angleOne
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getAngleone() {
        return angleone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.angleOne
     *
     * @param angleone the value for t_device_status.angleOne
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setAngleone(Integer angleone) {
        this.angleone = angleone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.angleTwo
     *
     * @return the value of t_device_status.angleTwo
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getAngletwo() {
        return angletwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.angleTwo
     *
     * @param angletwo the value for t_device_status.angleTwo
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setAngletwo(Integer angletwo) {
        this.angletwo = angletwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.angleOriginalOne
     *
     * @return the value of t_device_status.angleOriginalOne
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getAngleoriginalone() {
        return angleoriginalone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.angleOriginalOne
     *
     * @param angleoriginalone the value for t_device_status.angleOriginalOne
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setAngleoriginalone(Integer angleoriginalone) {
        this.angleoriginalone = angleoriginalone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.angleOriginalTwo
     *
     * @return the value of t_device_status.angleOriginalTwo
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public Integer getAngleoriginaltwo() {
        return angleoriginaltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.angleOriginalTwo
     *
     * @param angleoriginaltwo the value for t_device_status.angleOriginalTwo
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    public void setAngleoriginaltwo(Integer angleoriginaltwo) {
        this.angleoriginaltwo = angleoriginaltwo;
    }
}