package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

public class DeviceReportAngleAbnormal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_angleabnormal.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_angleabnormal.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_angleabnormal.abnormalflag
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Byte abnormalflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_angleabnormal.angleOne
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Integer angleone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_angleabnormal.angleTwo
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Integer angletwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_angleabnormal.angleOriginalOne
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Integer angleoriginalone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_angleabnormal.angleOriginalTwo
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Integer angleoriginaltwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_angleabnormal.angleThreadhold
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Integer anglethreadhold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_angleabnormal.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_angleabnormal.id
     *
     * @return the value of t_device_report_angleabnormal.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_angleabnormal.id
     *
     * @param id the value for t_device_report_angleabnormal.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_angleabnormal.imei
     *
     * @return the value of t_device_report_angleabnormal.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_angleabnormal.imei
     *
     * @param imei the value for t_device_report_angleabnormal.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_angleabnormal.abnormalflag
     *
     * @return the value of t_device_report_angleabnormal.abnormalflag
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Byte getAbnormalflag() {
        return abnormalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_angleabnormal.abnormalflag
     *
     * @param abnormalflag the value for t_device_report_angleabnormal.abnormalflag
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setAbnormalflag(Byte abnormalflag) {
        this.abnormalflag = abnormalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_angleabnormal.angleOne
     *
     * @return the value of t_device_report_angleabnormal.angleOne
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Integer getAngleone() {
        return angleone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_angleabnormal.angleOne
     *
     * @param angleone the value for t_device_report_angleabnormal.angleOne
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setAngleone(Integer angleone) {
        this.angleone = angleone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_angleabnormal.angleTwo
     *
     * @return the value of t_device_report_angleabnormal.angleTwo
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Integer getAngletwo() {
        return angletwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_angleabnormal.angleTwo
     *
     * @param angletwo the value for t_device_report_angleabnormal.angleTwo
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setAngletwo(Integer angletwo) {
        this.angletwo = angletwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_angleabnormal.angleOriginalOne
     *
     * @return the value of t_device_report_angleabnormal.angleOriginalOne
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Integer getAngleoriginalone() {
        return angleoriginalone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_angleabnormal.angleOriginalOne
     *
     * @param angleoriginalone the value for t_device_report_angleabnormal.angleOriginalOne
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setAngleoriginalone(Integer angleoriginalone) {
        this.angleoriginalone = angleoriginalone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_angleabnormal.angleOriginalTwo
     *
     * @return the value of t_device_report_angleabnormal.angleOriginalTwo
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Integer getAngleoriginaltwo() {
        return angleoriginaltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_angleabnormal.angleOriginalTwo
     *
     * @param angleoriginaltwo the value for t_device_report_angleabnormal.angleOriginalTwo
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setAngleoriginaltwo(Integer angleoriginaltwo) {
        this.angleoriginaltwo = angleoriginaltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_angleabnormal.angleThreadhold
     *
     * @return the value of t_device_report_angleabnormal.angleThreadhold
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Integer getAnglethreadhold() {
        return anglethreadhold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_angleabnormal.angleThreadhold
     *
     * @param anglethreadhold the value for t_device_report_angleabnormal.angleThreadhold
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setAnglethreadhold(Integer anglethreadhold) {
        this.anglethreadhold = anglethreadhold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_angleabnormal.time
     *
     * @return the value of t_device_report_angleabnormal.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_angleabnormal.time
     *
     * @param time the value for t_device_report_angleabnormal.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}