package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

import io.netty.channel.Channel;

public class DeviceMessage {
	
	private Channel  channel;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.id
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.imei
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.headHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    private String headhexstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.flagHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    private String flaghexstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.controlHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    private String controlhexstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.versionHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    private String versionhexstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.contentLengthHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    private String contentlengthhexstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.contentHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    private String contenthexstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.endsHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    private String endshexstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.time
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")        
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.id
     *
     * @return the value of t_message.id
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.id
     *
     * @param id the value for t_message.id
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.imei
     *
     * @return the value of t_message.imei
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.imei
     *
     * @param imei the value for t_message.imei
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.headHexStr
     *
     * @return the value of t_message.headHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public String getHeadhexstr() {
        return headhexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.headHexStr
     *
     * @param headhexstr the value for t_message.headHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public void setHeadhexstr(String headhexstr) {
        this.headhexstr = headhexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.flagHexStr
     *
     * @return the value of t_message.flagHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public String getFlaghexstr() {
        return flaghexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.flagHexStr
     *
     * @param flaghexstr the value for t_message.flagHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public void setFlaghexstr(String flaghexstr) {
        this.flaghexstr = flaghexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.controlHexStr
     *
     * @return the value of t_message.controlHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public String getControlhexstr() {
        return controlhexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.controlHexStr
     *
     * @param controlhexstr the value for t_message.controlHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public void setControlhexstr(String controlhexstr) {
        this.controlhexstr = controlhexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.versionHexStr
     *
     * @return the value of t_message.versionHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public String getVersionhexstr() {
        return versionhexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.versionHexStr
     *
     * @param versionhexstr the value for t_message.versionHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public void setVersionhexstr(String versionhexstr) {
        this.versionhexstr = versionhexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.contentLengthHexStr
     *
     * @return the value of t_message.contentLengthHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public String getContentlengthhexstr() {
        return contentlengthhexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.contentLengthHexStr
     *
     * @param contentlengthhexstr the value for t_message.contentLengthHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public void setContentlengthhexstr(String contentlengthhexstr) {
        this.contentlengthhexstr = contentlengthhexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.contentHexStr
     *
     * @return the value of t_message.contentHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public String getContenthexstr() {
        return contenthexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.contentHexStr
     *
     * @param contenthexstr the value for t_message.contentHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public void setContenthexstr(String contenthexstr) {
        this.contenthexstr = contenthexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.endsHexStr
     *
     * @return the value of t_message.endsHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public String getEndshexstr() {
        return endshexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.endsHexStr
     *
     * @param endshexstr the value for t_message.endsHexStr
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public void setEndshexstr(String endshexstr) {
        this.endshexstr = endshexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.time
     *
     * @return the value of t_message.time
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.time
     *
     * @param time the value for t_message.time
     *
     * @mbg.generated Sun Jan 19 15:45:57 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
    
	public String getHexStr() {
		if (versionhexstr != null) {
			return headhexstr + flaghexstr + controlhexstr + versionhexstr + contentlengthhexstr + contenthexstr
					+ endshexstr;

		} else {
			return headhexstr + flaghexstr + controlhexstr + contentlengthhexstr + contenthexstr + endshexstr;

		}
	}

	public Channel getChannel() {
		return channel;
	}

	public void setChannel(Channel channel) {
		this.channel = channel;
	}

	public DeviceMessage() {
		super();
		// TODO Auto-generated constructor stub
		this.headhexstr="6F01";
		this.endshexstr="0D0A0D0A";
		this.versionhexstr=null;
	}
	
	
}