package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

public class DeviceReportCellId {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_cellid.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_cellid.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_cellid.cellid
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Integer cellid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_cellid.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_cellid.id
     *
     * @return the value of t_device_report_cellid.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_cellid.id
     *
     * @param id the value for t_device_report_cellid.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_cellid.imei
     *
     * @return the value of t_device_report_cellid.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_cellid.imei
     *
     * @param imei the value for t_device_report_cellid.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_cellid.cellid
     *
     * @return the value of t_device_report_cellid.cellid
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Integer getCellid() {
        return cellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_cellid.cellid
     *
     * @param cellid the value for t_device_report_cellid.cellid
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setCellid(Integer cellid) {
        this.cellid = cellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_cellid.time
     *
     * @return the value of t_device_report_cellid.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_cellid.time
     *
     * @param time the value for t_device_report_cellid.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}