package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

public class DeviceReportHardVersion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_hardversion.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_hardversion.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_hardversion.hardversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private String hardversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_report_hardversion.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_hardversion.id
     *
     * @return the value of t_device_report_hardversion.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_hardversion.id
     *
     * @param id the value for t_device_report_hardversion.id
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_hardversion.imei
     *
     * @return the value of t_device_report_hardversion.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_hardversion.imei
     *
     * @param imei the value for t_device_report_hardversion.imei
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_hardversion.hardversion
     *
     * @return the value of t_device_report_hardversion.hardversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public String getHardversion() {
        return hardversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_hardversion.hardversion
     *
     * @param hardversion the value for t_device_report_hardversion.hardversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setHardversion(String hardversion) {
        this.hardversion = hardversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_report_hardversion.time
     *
     * @return the value of t_device_report_hardversion.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_report_hardversion.time
     *
     * @param time the value for t_device_report_hardversion.time
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}