package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

/**
*
* 发送给设备的信息 ，接收到设备的信息
*
* @mbg.generated Mon Jan 20 14:56:26 CST 2020
*/
public class DeviceResponse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_response.id
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_response.imei
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_response.controlHexStr
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    private String controlhexstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_response.mid
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_response.errorCode
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    private Byte errorcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_response.time
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_response.id
     *
     * @return the value of t_device_response.id
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_response.id
     *
     * @param id the value for t_device_response.id
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_response.imei
     *
     * @return the value of t_device_response.imei
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_response.imei
     *
     * @param imei the value for t_device_response.imei
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_response.controlHexStr
     *
     * @return the value of t_device_response.controlHexStr
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    public String getControlhexstr() {
        return controlhexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_response.controlHexStr
     *
     * @param controlhexstr the value for t_device_response.controlHexStr
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    public void setControlhexstr(String controlhexstr) {
        this.controlhexstr = controlhexstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_response.mid
     *
     * @return the value of t_device_response.mid
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_response.mid
     *
     * @param mid the value for t_device_response.mid
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_response.errorCode
     *
     * @return the value of t_device_response.errorCode
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    public Byte getErrorcode() {
        return errorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_response.errorCode
     *
     * @param errorcode the value for t_device_response.errorCode
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    public void setErrorcode(Byte errorcode) {
        this.errorcode = errorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_response.time
     *
     * @return the value of t_device_response.time
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_response.time
     *
     * @param time the value for t_device_response.time
     *
     * @mbg.generated Mon Jan 20 10:28:26 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}