package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

public class ServiceSettingsDeviceInstallationstateAnglethreadhold {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_installationstate_anglethreadhold.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_installationstate_anglethreadhold.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_installationstate_anglethreadhold.installationStable
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer installationstable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_installationstate_anglethreadhold.angleThreadhold
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer anglethreadhold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_installationstate_anglethreadhold.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_installationstate_anglethreadhold.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_installationstate_anglethreadhold.id
     *
     * @return the value of t_service_settings_device_installationstate_anglethreadhold.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_installationstate_anglethreadhold.id
     *
     * @param id the value for t_service_settings_device_installationstate_anglethreadhold.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_installationstate_anglethreadhold.imei
     *
     * @return the value of t_service_settings_device_installationstate_anglethreadhold.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_installationstate_anglethreadhold.imei
     *
     * @param imei the value for t_service_settings_device_installationstate_anglethreadhold.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_installationstate_anglethreadhold.installationStable
     *
     * @return the value of t_service_settings_device_installationstate_anglethreadhold.installationStable
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getInstallationstable() {
        return installationstable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_installationstate_anglethreadhold.installationStable
     *
     * @param installationstable the value for t_service_settings_device_installationstate_anglethreadhold.installationStable
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setInstallationstable(Integer installationstable) {
        this.installationstable = installationstable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_installationstate_anglethreadhold.angleThreadhold
     *
     * @return the value of t_service_settings_device_installationstate_anglethreadhold.angleThreadhold
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getAnglethreadhold() {
        return anglethreadhold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_installationstate_anglethreadhold.angleThreadhold
     *
     * @param anglethreadhold the value for t_service_settings_device_installationstate_anglethreadhold.angleThreadhold
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setAnglethreadhold(Integer anglethreadhold) {
        this.anglethreadhold = anglethreadhold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_installationstate_anglethreadhold.mid
     *
     * @return the value of t_service_settings_device_installationstate_anglethreadhold.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_installationstate_anglethreadhold.mid
     *
     * @param mid the value for t_service_settings_device_installationstate_anglethreadhold.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_installationstate_anglethreadhold.time
     *
     * @return the value of t_service_settings_device_installationstate_anglethreadhold.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_installationstate_anglethreadhold.time
     *
     * @param time the value for t_service_settings_device_installationstate_anglethreadhold.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}