package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

public class ServiceSettingsDevicePowerConsumption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_powerconsumption.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_powerconsumption.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_powerconsumption.powerConsumptionIntegerPart
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer powerconsumptionintegerpart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_powerconsumption.powerConsumptionDecimalPart
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer powerconsumptiondecimalpart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_powerconsumption.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_powerconsumption.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_powerconsumption.id
     *
     * @return the value of t_service_settings_device_powerconsumption.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_powerconsumption.id
     *
     * @param id the value for t_service_settings_device_powerconsumption.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_powerconsumption.imei
     *
     * @return the value of t_service_settings_device_powerconsumption.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_powerconsumption.imei
     *
     * @param imei the value for t_service_settings_device_powerconsumption.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_powerconsumption.powerConsumptionIntegerPart
     *
     * @return the value of t_service_settings_device_powerconsumption.powerConsumptionIntegerPart
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getPowerconsumptionintegerpart() {
        return powerconsumptionintegerpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_powerconsumption.powerConsumptionIntegerPart
     *
     * @param powerconsumptionintegerpart the value for t_service_settings_device_powerconsumption.powerConsumptionIntegerPart
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setPowerconsumptionintegerpart(Integer powerconsumptionintegerpart) {
        this.powerconsumptionintegerpart = powerconsumptionintegerpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_powerconsumption.powerConsumptionDecimalPart
     *
     * @return the value of t_service_settings_device_powerconsumption.powerConsumptionDecimalPart
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getPowerconsumptiondecimalpart() {
        return powerconsumptiondecimalpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_powerconsumption.powerConsumptionDecimalPart
     *
     * @param powerconsumptiondecimalpart the value for t_service_settings_device_powerconsumption.powerConsumptionDecimalPart
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setPowerconsumptiondecimalpart(Integer powerconsumptiondecimalpart) {
        this.powerconsumptiondecimalpart = powerconsumptiondecimalpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_powerconsumption.mid
     *
     * @return the value of t_service_settings_device_powerconsumption.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_powerconsumption.mid
     *
     * @param mid the value for t_service_settings_device_powerconsumption.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_powerconsumption.time
     *
     * @return the value of t_service_settings_device_powerconsumption.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_powerconsumption.time
     *
     * @param time the value for t_service_settings_device_powerconsumption.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}