package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

public class ServiceSettingsDeviceReportInterval {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_reportinterval.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_reportinterval.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_reportinterval.reportInterval
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer reportinterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_reportinterval.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_reportinterval.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_reportinterval.id
     *
     * @return the value of t_service_settings_device_reportinterval.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_reportinterval.id
     *
     * @param id the value for t_service_settings_device_reportinterval.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_reportinterval.imei
     *
     * @return the value of t_service_settings_device_reportinterval.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_reportinterval.imei
     *
     * @param imei the value for t_service_settings_device_reportinterval.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_reportinterval.reportInterval
     *
     * @return the value of t_service_settings_device_reportinterval.reportInterval
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getReportinterval() {
        return reportinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_reportinterval.reportInterval
     *
     * @param reportinterval the value for t_service_settings_device_reportinterval.reportInterval
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setReportinterval(Integer reportinterval) {
        this.reportinterval = reportinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_reportinterval.mid
     *
     * @return the value of t_service_settings_device_reportinterval.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_reportinterval.mid
     *
     * @param mid the value for t_service_settings_device_reportinterval.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_reportinterval.time
     *
     * @return the value of t_service_settings_device_reportinterval.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_reportinterval.time
     *
     * @param time the value for t_service_settings_device_reportinterval.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}