package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

public class ServiceSettingsDeviceBrightness {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_brightness.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_brightness.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_brightness.brightnessControlOne
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer brightnesscontrolone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_brightness.brightnessControlTwo
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer brightnesscontroltwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_brightness.brightnessControlThree
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer brightnesscontrolthree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_brightness.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_brightness.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_brightness.id
     *
     * @return the value of t_service_settings_device_brightness.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_brightness.id
     *
     * @param id the value for t_service_settings_device_brightness.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_brightness.imei
     *
     * @return the value of t_service_settings_device_brightness.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_brightness.imei
     *
     * @param imei the value for t_service_settings_device_brightness.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_brightness.brightnessControlOne
     *
     * @return the value of t_service_settings_device_brightness.brightnessControlOne
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getBrightnesscontrolone() {
        return brightnesscontrolone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_brightness.brightnessControlOne
     *
     * @param brightnesscontrolone the value for t_service_settings_device_brightness.brightnessControlOne
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setBrightnesscontrolone(Integer brightnesscontrolone) {
        this.brightnesscontrolone = brightnesscontrolone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_brightness.brightnessControlTwo
     *
     * @return the value of t_service_settings_device_brightness.brightnessControlTwo
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getBrightnesscontroltwo() {
        return brightnesscontroltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_brightness.brightnessControlTwo
     *
     * @param brightnesscontroltwo the value for t_service_settings_device_brightness.brightnessControlTwo
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setBrightnesscontroltwo(Integer brightnesscontroltwo) {
        this.brightnesscontroltwo = brightnesscontroltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_brightness.brightnessControlThree
     *
     * @return the value of t_service_settings_device_brightness.brightnessControlThree
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getBrightnesscontrolthree() {
        return brightnesscontrolthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_brightness.brightnessControlThree
     *
     * @param brightnesscontrolthree the value for t_service_settings_device_brightness.brightnessControlThree
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setBrightnesscontrolthree(Integer brightnesscontrolthree) {
        this.brightnesscontrolthree = brightnesscontrolthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_brightness.mid
     *
     * @return the value of t_service_settings_device_brightness.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_brightness.mid
     *
     * @param mid the value for t_service_settings_device_brightness.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_brightness.time
     *
     * @return the value of t_service_settings_device_brightness.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_brightness.time
     *
     * @param time the value for t_service_settings_device_brightness.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}