package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

public class ServiceSettingsDeviceTime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_time.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_time.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_time.year
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_time.month
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_time.day
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_time.hour
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_time.minute
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer minute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_time.second
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer second;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_time.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_time.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_time.id
     *
     * @return the value of t_service_settings_device_time.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_time.id
     *
     * @param id the value for t_service_settings_device_time.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_time.imei
     *
     * @return the value of t_service_settings_device_time.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_time.imei
     *
     * @param imei the value for t_service_settings_device_time.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_time.year
     *
     * @return the value of t_service_settings_device_time.year
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_time.year
     *
     * @param year the value for t_service_settings_device_time.year
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_time.month
     *
     * @return the value of t_service_settings_device_time.month
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_time.month
     *
     * @param month the value for t_service_settings_device_time.month
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_time.day
     *
     * @return the value of t_service_settings_device_time.day
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_time.day
     *
     * @param day the value for t_service_settings_device_time.day
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_time.hour
     *
     * @return the value of t_service_settings_device_time.hour
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_time.hour
     *
     * @param hour the value for t_service_settings_device_time.hour
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_time.minute
     *
     * @return the value of t_service_settings_device_time.minute
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getMinute() {
        return minute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_time.minute
     *
     * @param minute the value for t_service_settings_device_time.minute
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setMinute(Integer minute) {
        this.minute = minute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_time.second
     *
     * @return the value of t_service_settings_device_time.second
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getSecond() {
        return second;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_time.second
     *
     * @param second the value for t_service_settings_device_time.second
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setSecond(Integer second) {
        this.second = second;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_time.mid
     *
     * @return the value of t_service_settings_device_time.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_time.mid
     *
     * @param mid the value for t_service_settings_device_time.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_time.time
     *
     * @return the value of t_service_settings_device_time.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_time.time
     *
     * @param time the value for t_service_settings_device_time.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}