package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

public class ServiceSettingsDeviceLightingStrategy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_lightingstrategy.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_lightingstrategy.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_lightingstrategy.lightNum
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer lightnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_lightingstrategy.strategyNum
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer strategynum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_lightingstrategy.strategyPeriod
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer strategyperiod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_lightingstrategy.timeNum
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Integer timenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_lightingstrategy.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_lightingstrategy.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_lightingstrategy.timehex
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    private String timehex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_lightingstrategy.id
     *
     * @return the value of t_service_settings_device_lightingstrategy.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_lightingstrategy.id
     *
     * @param id the value for t_service_settings_device_lightingstrategy.id
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_lightingstrategy.imei
     *
     * @return the value of t_service_settings_device_lightingstrategy.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_lightingstrategy.imei
     *
     * @param imei the value for t_service_settings_device_lightingstrategy.imei
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_lightingstrategy.lightNum
     *
     * @return the value of t_service_settings_device_lightingstrategy.lightNum
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getLightnum() {
        return lightnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_lightingstrategy.lightNum
     *
     * @param lightnum the value for t_service_settings_device_lightingstrategy.lightNum
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setLightnum(Integer lightnum) {
        this.lightnum = lightnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_lightingstrategy.strategyNum
     *
     * @return the value of t_service_settings_device_lightingstrategy.strategyNum
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getStrategynum() {
        return strategynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_lightingstrategy.strategyNum
     *
     * @param strategynum the value for t_service_settings_device_lightingstrategy.strategyNum
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setStrategynum(Integer strategynum) {
        this.strategynum = strategynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_lightingstrategy.strategyPeriod
     *
     * @return the value of t_service_settings_device_lightingstrategy.strategyPeriod
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getStrategyperiod() {
        return strategyperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_lightingstrategy.strategyPeriod
     *
     * @param strategyperiod the value for t_service_settings_device_lightingstrategy.strategyPeriod
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setStrategyperiod(Integer strategyperiod) {
        this.strategyperiod = strategyperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_lightingstrategy.timeNum
     *
     * @return the value of t_service_settings_device_lightingstrategy.timeNum
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Integer getTimenum() {
        return timenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_lightingstrategy.timeNum
     *
     * @param timenum the value for t_service_settings_device_lightingstrategy.timeNum
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setTimenum(Integer timenum) {
        this.timenum = timenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_lightingstrategy.mid
     *
     * @return the value of t_service_settings_device_lightingstrategy.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_lightingstrategy.mid
     *
     * @param mid the value for t_service_settings_device_lightingstrategy.mid
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_lightingstrategy.time
     *
     * @return the value of t_service_settings_device_lightingstrategy.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_lightingstrategy.time
     *
     * @param time the value for t_service_settings_device_lightingstrategy.time
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_lightingstrategy.timehex
     *
     * @return the value of t_service_settings_device_lightingstrategy.timehex
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public String getTimehex() {
        return timehex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_lightingstrategy.timehex
     *
     * @param timehex the value for t_service_settings_device_lightingstrategy.timehex
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    public void setTimehex(String timehex) {
        this.timehex = timehex;
    }
}