package com.viroyal.doormagnet.devicemng.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

/*
 * 控制器1~3路灯开/关
 */
public class ServiceSettingsDeviceSwitch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_switch.id
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_switch.imei
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_switch.switchControlOne
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    private Integer switchcontrolone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_switch.switchControlTwo
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    private Integer switchcontroltwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_switch.switchControlThree
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    private Integer switchcontrolthree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_switch.mid
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_service_settings_device_switch.time
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")       
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_switch.id
     *
     * @return the value of t_service_settings_device_switch.id
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_switch.id
     *
     * @param id the value for t_service_settings_device_switch.id
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_switch.imei
     *
     * @return the value of t_service_settings_device_switch.imei
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_switch.imei
     *
     * @param imei the value for t_service_settings_device_switch.imei
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_switch.switchControlOne
     *
     * @return the value of t_service_settings_device_switch.switchControlOne
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public Integer getSwitchcontrolone() {
        return switchcontrolone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_switch.switchControlOne
     *
     * @param switchcontrolone the value for t_service_settings_device_switch.switchControlOne
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public void setSwitchcontrolone(Integer switchcontrolone) {
        this.switchcontrolone = switchcontrolone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_switch.switchControlTwo
     *
     * @return the value of t_service_settings_device_switch.switchControlTwo
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public Integer getSwitchcontroltwo() {
        return switchcontroltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_switch.switchControlTwo
     *
     * @param switchcontroltwo the value for t_service_settings_device_switch.switchControlTwo
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public void setSwitchcontroltwo(Integer switchcontroltwo) {
        this.switchcontroltwo = switchcontroltwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_switch.switchControlThree
     *
     * @return the value of t_service_settings_device_switch.switchControlThree
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public Integer getSwitchcontrolthree() {
        return switchcontrolthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_switch.switchControlThree
     *
     * @param switchcontrolthree the value for t_service_settings_device_switch.switchControlThree
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public void setSwitchcontrolthree(Integer switchcontrolthree) {
        this.switchcontrolthree = switchcontrolthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_switch.mid
     *
     * @return the value of t_service_settings_device_switch.mid
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_switch.mid
     *
     * @param mid the value for t_service_settings_device_switch.mid
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_service_settings_device_switch.time
     *
     * @return the value of t_service_settings_device_switch.time
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_service_settings_device_switch.time
     *
     * @param time the value for t_service_settings_device_switch.time
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}