package com.viroyal.doormagnet.modules.system.model;

import java.util.Date;

public class SysAnnouncementSend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement_send.id
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement_send.annt_id
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    private String anntId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement_send.user_id
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement_send.read_flag
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    private String readFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement_send.read_time
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    private Date readTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement_send.create_by
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement_send.create_time
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement_send.update_by
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement_send.update_time
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement_send.id
     *
     * @return the value of sys_announcement_send.id
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement_send.id
     *
     * @param id the value for sys_announcement_send.id
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement_send.annt_id
     *
     * @return the value of sys_announcement_send.annt_id
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public String getAnntId() {
        return anntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement_send.annt_id
     *
     * @param anntId the value for sys_announcement_send.annt_id
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public void setAnntId(String anntId) {
        this.anntId = anntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement_send.user_id
     *
     * @return the value of sys_announcement_send.user_id
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement_send.user_id
     *
     * @param userId the value for sys_announcement_send.user_id
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement_send.read_flag
     *
     * @return the value of sys_announcement_send.read_flag
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public String getReadFlag() {
        return readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement_send.read_flag
     *
     * @param readFlag the value for sys_announcement_send.read_flag
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public void setReadFlag(String readFlag) {
        this.readFlag = readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement_send.read_time
     *
     * @return the value of sys_announcement_send.read_time
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement_send.read_time
     *
     * @param readTime the value for sys_announcement_send.read_time
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement_send.create_by
     *
     * @return the value of sys_announcement_send.create_by
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement_send.create_by
     *
     * @param createBy the value for sys_announcement_send.create_by
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement_send.create_time
     *
     * @return the value of sys_announcement_send.create_time
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement_send.create_time
     *
     * @param createTime the value for sys_announcement_send.create_time
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement_send.update_by
     *
     * @return the value of sys_announcement_send.update_by
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement_send.update_by
     *
     * @param updateBy the value for sys_announcement_send.update_by
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement_send.update_time
     *
     * @return the value of sys_announcement_send.update_time
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement_send.update_time
     *
     * @param updateTime the value for sys_announcement_send.update_time
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}