package com.viroyal.doormagnet.modules.system.model;

import java.util.Date;

public class SysPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.id
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.parent_id
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.name
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.url
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.component
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.component_name
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String componentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.redirect
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String redirect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.menu_type
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private Integer menuType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.perms
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String perms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.perms_type
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String permsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.sort_no
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private Double sortNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.always_show
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private Boolean alwaysShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.icon
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.is_route
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private Boolean isRoute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.is_leaf
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private Boolean isLeaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.keep_alive
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private Boolean keepAlive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.hidden
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private Integer hidden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.description
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.create_by
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.create_time
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.update_by
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.update_time
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.del_flag
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.rule_flag
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private Integer ruleFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.status
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.internal_or_external
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    private Boolean internalOrExternal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.id
     *
     * @return the value of sys_permission.id
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.id
     *
     * @param id the value for sys_permission.id
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.parent_id
     *
     * @return the value of sys_permission.parent_id
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.parent_id
     *
     * @param parentId the value for sys_permission.parent_id
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.name
     *
     * @return the value of sys_permission.name
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.name
     *
     * @param name the value for sys_permission.name
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.url
     *
     * @return the value of sys_permission.url
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.url
     *
     * @param url the value for sys_permission.url
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.component
     *
     * @return the value of sys_permission.component
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.component
     *
     * @param component the value for sys_permission.component
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setComponent(String component) {
        this.component = component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.component_name
     *
     * @return the value of sys_permission.component_name
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.component_name
     *
     * @param componentName the value for sys_permission.component_name
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setComponentName(String componentName) {
        this.componentName = componentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.redirect
     *
     * @return the value of sys_permission.redirect
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getRedirect() {
        return redirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.redirect
     *
     * @param redirect the value for sys_permission.redirect
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setRedirect(String redirect) {
        this.redirect = redirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.menu_type
     *
     * @return the value of sys_permission.menu_type
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public Integer getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.menu_type
     *
     * @param menuType the value for sys_permission.menu_type
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.perms
     *
     * @return the value of sys_permission.perms
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.perms
     *
     * @param perms the value for sys_permission.perms
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setPerms(String perms) {
        this.perms = perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.perms_type
     *
     * @return the value of sys_permission.perms_type
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getPermsType() {
        return permsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.perms_type
     *
     * @param permsType the value for sys_permission.perms_type
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setPermsType(String permsType) {
        this.permsType = permsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.sort_no
     *
     * @return the value of sys_permission.sort_no
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public Double getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.sort_no
     *
     * @param sortNo the value for sys_permission.sort_no
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setSortNo(Double sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.always_show
     *
     * @return the value of sys_permission.always_show
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public Boolean getAlwaysShow() {
        return alwaysShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.always_show
     *
     * @param alwaysShow the value for sys_permission.always_show
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setAlwaysShow(Boolean alwaysShow) {
        this.alwaysShow = alwaysShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.icon
     *
     * @return the value of sys_permission.icon
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.icon
     *
     * @param icon the value for sys_permission.icon
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.is_route
     *
     * @return the value of sys_permission.is_route
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public Boolean getIsRoute() {
        return isRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.is_route
     *
     * @param isRoute the value for sys_permission.is_route
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setIsRoute(Boolean isRoute) {
        this.isRoute = isRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.is_leaf
     *
     * @return the value of sys_permission.is_leaf
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public Boolean getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.is_leaf
     *
     * @param isLeaf the value for sys_permission.is_leaf
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setIsLeaf(Boolean isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.keep_alive
     *
     * @return the value of sys_permission.keep_alive
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public Boolean getKeepAlive() {
        return keepAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.keep_alive
     *
     * @param keepAlive the value for sys_permission.keep_alive
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setKeepAlive(Boolean keepAlive) {
        this.keepAlive = keepAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.hidden
     *
     * @return the value of sys_permission.hidden
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public Integer getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.hidden
     *
     * @param hidden the value for sys_permission.hidden
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setHidden(Integer hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.description
     *
     * @return the value of sys_permission.description
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.description
     *
     * @param description the value for sys_permission.description
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.create_by
     *
     * @return the value of sys_permission.create_by
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.create_by
     *
     * @param createBy the value for sys_permission.create_by
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.create_time
     *
     * @return the value of sys_permission.create_time
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.create_time
     *
     * @param createTime the value for sys_permission.create_time
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.update_by
     *
     * @return the value of sys_permission.update_by
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.update_by
     *
     * @param updateBy the value for sys_permission.update_by
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.update_time
     *
     * @return the value of sys_permission.update_time
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.update_time
     *
     * @param updateTime the value for sys_permission.update_time
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.del_flag
     *
     * @return the value of sys_permission.del_flag
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.del_flag
     *
     * @param delFlag the value for sys_permission.del_flag
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.rule_flag
     *
     * @return the value of sys_permission.rule_flag
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public Integer getRuleFlag() {
        return ruleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.rule_flag
     *
     * @param ruleFlag the value for sys_permission.rule_flag
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setRuleFlag(Integer ruleFlag) {
        this.ruleFlag = ruleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.status
     *
     * @return the value of sys_permission.status
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.status
     *
     * @param status the value for sys_permission.status
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.internal_or_external
     *
     * @return the value of sys_permission.internal_or_external
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public Boolean getInternalOrExternal() {
        return internalOrExternal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.internal_or_external
     *
     * @param internalOrExternal the value for sys_permission.internal_or_external
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    public void setInternalOrExternal(Boolean internalOrExternal) {
        this.internalOrExternal = internalOrExternal;
    }
}