package com.viroyal.doormagnet.modules.system.mapper;

import com.viroyal.doormagnet.modules.system.model.SysAnnouncementSend;

public interface SysAnnouncementSendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement_send
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    int insert(SysAnnouncementSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement_send
     *
     * @mbg.generated Wed Mar 25 10:54:21 CST 2020
     */
    int insertSelective(SysAnnouncementSend record);
}