package com.viroyal.doormagnet.modules.system.mapper;

import com.viroyal.doormagnet.modules.system.model.SysAnnouncement;
import com.viroyal.doormagnet.modules.system.model.SysAnnouncementWithBLOBs;

public interface SysAnnouncementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement
     *
     * @mbg.generated Wed Mar 25 10:01:15 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement
     *
     * @mbg.generated Wed Mar 25 10:01:15 CST 2020
     */
    int insert(SysAnnouncementWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement
     *
     * @mbg.generated Wed Mar 25 10:01:15 CST 2020
     */
    int insertSelective(SysAnnouncementWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement
     *
     * @mbg.generated Wed Mar 25 10:01:15 CST 2020
     */
    SysAnnouncementWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement
     *
     * @mbg.generated Wed Mar 25 10:01:15 CST 2020
     */
    int updateByPrimaryKeySelective(SysAnnouncementWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement
     *
     * @mbg.generated Wed Mar 25 10:01:15 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(SysAnnouncementWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement
     *
     * @mbg.generated Wed Mar 25 10:01:15 CST 2020
     */
    int updateByPrimaryKey(SysAnnouncement record);
}