package com.viroyal.doormagnet.modules.system.mapper;

import java.util.List;

import com.viroyal.doormagnet.modules.system.model.SysPermission;

public interface SysPermissionMapper {

	List<SysPermission> queryByUser(String username);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    int insert(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    int insertSelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    SysPermission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    int updateByPrimaryKeySelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Mon Mar 23 11:02:42 CST 2020
     */
    int updateByPrimaryKey(SysPermission record);
}