package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.DeviceReportAngleAbnormal;

public interface DeviceReportAngleAbnormalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_angleabnormal
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_angleabnormal
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int insert(DeviceReportAngleAbnormal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_angleabnormal
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int insertSelective(DeviceReportAngleAbnormal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_angleabnormal
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    DeviceReportAngleAbnormal selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_angleabnormal
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceReportAngleAbnormal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_angleabnormal
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int updateByPrimaryKey(DeviceReportAngleAbnormal record);
}