package com.viroyal.doormagnet.devicemng.mapper;

import org.apache.ibatis.annotations.Param;

import com.viroyal.doormagnet.devicemng.model.DeviceResponse;

public interface DeviceResponseMapper {
	DeviceResponse findLastresponse(@Param("imei")String imei, @Param("controlhexstr")String controlhexstr);

	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_response
     *
     * @mbg.generated Sun Jan 19 16:40:52 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_response
     *
     * @mbg.generated Sun Jan 19 16:40:52 CST 2020
     */
    int insert(DeviceResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_response
     *
     * @mbg.generated Sun Jan 19 16:40:52 CST 2020
     */
    int insertSelective(DeviceResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_response
     *
     * @mbg.generated Sun Jan 19 16:40:52 CST 2020
     */
    DeviceResponse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_response
     *
     * @mbg.generated Sun Jan 19 16:40:52 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_response
     *
     * @mbg.generated Sun Jan 19 16:40:52 CST 2020
     */
    int updateByPrimaryKey(DeviceResponse record);
}