package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.DeviceStatus;

public interface DeviceStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_status
     *
     * @mbg.generated Thu Jan 16 14:55:49 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_status
     *
     * @mbg.generated Thu Jan 16 14:55:49 CST 2020
     */
    int insert(DeviceStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_status
     *
     * @mbg.generated Thu Jan 16 14:55:49 CST 2020
     */
    int insertSelective(DeviceStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_status
     *
     * @mbg.generated Thu Jan 16 14:55:49 CST 2020
     */
    DeviceStatus selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_status
     *
     * @mbg.generated Thu Jan 16 14:55:49 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_status
     *
     * @mbg.generated Thu Jan 16 14:55:49 CST 2020
     */
    int updateByPrimaryKey(DeviceStatus record);
}