package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.DeviceReportHeartBeat;

public interface DeviceReportHeartBeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_heartbeat
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_heartbeat
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int insert(DeviceReportHeartBeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_heartbeat
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int insertSelective(DeviceReportHeartBeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_heartbeat
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    DeviceReportHeartBeat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_heartbeat
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceReportHeartBeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_heartbeat
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int updateByPrimaryKey(DeviceReportHeartBeat record);
}