package com.viroyal.doormagnet.devicemng.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.viroyal.doormagnet.devicemng.model.DeviceStatus;

@Mapper  //  该注解一定要加，否则无法映射到mybatis的***.xml局部配置文件
public interface DeviceStatusMapper {
    
    List<DeviceStatus> selectByImei(String imei);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_status
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_status
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    int insert(DeviceStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_status
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    int insertSelective(DeviceStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_status
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    DeviceStatus selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_status
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_status
     *
     * @mbg.generated Wed Jan 15 16:57:54 CST 2020
     */
    int updateByPrimaryKey(DeviceStatus record);
}