package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.DeviceReportCellId;

public interface DeviceReportCellIdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_cellid
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_cellid
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int insert(DeviceReportCellId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_cellid
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int insertSelective(DeviceReportCellId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_cellid
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    DeviceReportCellId selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_cellid
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceReportCellId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_cellid
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int updateByPrimaryKey(DeviceReportCellId record);
}