package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.DeviceSwitchSetting;

public interface DeviceSwitchSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_switch_setting
     *
     * @mbg.generated Thu Jan 16 17:52:21 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_switch_setting
     *
     * @mbg.generated Thu Jan 16 17:52:21 CST 2020
     */
    int insert(DeviceSwitchSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_switch_setting
     *
     * @mbg.generated Thu Jan 16 17:52:21 CST 2020
     */
    int insertSelective(DeviceSwitchSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_switch_setting
     *
     * @mbg.generated Thu Jan 16 17:52:21 CST 2020
     */
    DeviceSwitchSetting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_switch_setting
     *
     * @mbg.generated Thu Jan 16 17:52:21 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceSwitchSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_switch_setting
     *
     * @mbg.generated Thu Jan 16 17:52:21 CST 2020
     */
    int updateByPrimaryKey(DeviceSwitchSetting record);
}