package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.DeviceReportLightAbnormal;

public interface DeviceReportLightAbnormalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_lightabnormal
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_lightabnormal
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int insert(DeviceReportLightAbnormal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_lightabnormal
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int insertSelective(DeviceReportLightAbnormal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_lightabnormal
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    DeviceReportLightAbnormal selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_lightabnormal
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceReportLightAbnormal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_lightabnormal
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int updateByPrimaryKey(DeviceReportLightAbnormal record);
}