package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.DeviceReportSoftVersion;

public interface DeviceReportSoftVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_softversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_softversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int insert(DeviceReportSoftVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_softversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int insertSelective(DeviceReportSoftVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_softversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    DeviceReportSoftVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_softversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceReportSoftVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_softversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int updateByPrimaryKey(DeviceReportSoftVersion record);
}