package com.viroyal.doormagnet.devicemng.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.viroyal.doormagnet.devicemng.model.DeviceMessage;

public interface DeviceMessageMapper {
	
	List<DeviceMessage> queryByLimit(@Param("offset") Integer offset, @Param("limit") Integer limit);

    int insertOrUpdate(DeviceMessage record);

	int deleteByImeiAndControl(@Param("imei")String imei, @Param("controlhexstr")String controlhexstr);
	List<DeviceMessage> selectByImei(@Param("imei")String imei);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Mon Jan 20 14:56:26 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Mon Jan 20 14:56:26 CST 2020
     */
    int insert(DeviceMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Mon Jan 20 14:56:26 CST 2020
     */
    int insertSelective(DeviceMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Mon Jan 20 14:56:26 CST 2020
     */
    DeviceMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Mon Jan 20 14:56:26 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Mon Jan 20 14:56:26 CST 2020
     */
    int updateByPrimaryKey(DeviceMessage record);
}