package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.DeviceReportHardVersion;

public interface DeviceReportHardVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_hardversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_hardversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int insert(DeviceReportHardVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_hardversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int insertSelective(DeviceReportHardVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_hardversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    DeviceReportHardVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_hardversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceReportHardVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_report_hardversion
     *
     * @mbg.generated Tue Mar 17 14:21:33 CST 2020
     */
    int updateByPrimaryKey(DeviceReportHardVersion record);
}