package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.ServiceSettingsDeviceSwitch;

public interface ServiceSettingsDeviceSwitchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_switch
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_switch
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    int insert(ServiceSettingsDeviceSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_switch
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    int insertSelective(ServiceSettingsDeviceSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_switch
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    ServiceSettingsDeviceSwitch selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_switch
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    int updateByPrimaryKeySelective(ServiceSettingsDeviceSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_switch
     *
     * @mbg.generated Fri Jan 17 16:35:56 CST 2020
     */
    int updateByPrimaryKey(ServiceSettingsDeviceSwitch record);
}