package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.ServiceSettingsDevicePowerConsumption;

public interface ServiceSettingsDevicePowerConsumptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_powerconsumption
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_powerconsumption
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int insert(ServiceSettingsDevicePowerConsumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_powerconsumption
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int insertSelective(ServiceSettingsDevicePowerConsumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_powerconsumption
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    ServiceSettingsDevicePowerConsumption selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_powerconsumption
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int updateByPrimaryKeySelective(ServiceSettingsDevicePowerConsumption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_powerconsumption
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int updateByPrimaryKey(ServiceSettingsDevicePowerConsumption record);
}