package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.ServiceSettingsDeviceLightingStrategy;

public interface ServiceSettingsDeviceLightingStrategyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_lightingstrategy
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_lightingstrategy
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int insert(ServiceSettingsDeviceLightingStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_lightingstrategy
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int insertSelective(ServiceSettingsDeviceLightingStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_lightingstrategy
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    ServiceSettingsDeviceLightingStrategy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_lightingstrategy
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int updateByPrimaryKeySelective(ServiceSettingsDeviceLightingStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_lightingstrategy
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ServiceSettingsDeviceLightingStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_lightingstrategy
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int updateByPrimaryKey(ServiceSettingsDeviceLightingStrategy record);
}