package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.ServiceSettingsDeviceReportInterval;

public interface ServiceSettingsDeviceReportIntervalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_reportinterval
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_reportinterval
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int insert(ServiceSettingsDeviceReportInterval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_reportinterval
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int insertSelective(ServiceSettingsDeviceReportInterval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_reportinterval
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    ServiceSettingsDeviceReportInterval selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_reportinterval
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int updateByPrimaryKeySelective(ServiceSettingsDeviceReportInterval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_settings_device_reportinterval
     *
     * @mbg.generated Mon Mar 16 14:36:40 CST 2020
     */
    int updateByPrimaryKey(ServiceSettingsDeviceReportInterval record);
}