package com.viroyal.doormagnet.devicemng.mapper;

import com.viroyal.doormagnet.devicemng.model.ServiceResponse;

public interface ServiceResponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_response
     *
     * @mbg.generated Mon Jan 20 12:47:57 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_response
     *
     * @mbg.generated Mon Jan 20 12:47:57 CST 2020
     */
    int insert(ServiceResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_response
     *
     * @mbg.generated Mon Jan 20 12:47:57 CST 2020
     */
    int insertSelective(ServiceResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_response
     *
     * @mbg.generated Mon Jan 20 12:47:57 CST 2020
     */
    ServiceResponse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_response
     *
     * @mbg.generated Mon Jan 20 12:47:57 CST 2020
     */
    int updateByPrimaryKeySelective(ServiceResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_service_response
     *
     * @mbg.generated Mon Jan 20 12:47:57 CST 2020
     */
    int updateByPrimaryKey(ServiceResponse record);
}